name: declarative_navigation
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.5.2
  go_router: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
